Contacts modal
mkundeev/team-project pull request #21
Opened 2022-04-23 22:09 UTC by KocherhanIrina

tablet desktop

2022-04-24 07:53 UTC, mkundeev requested changes

2022-04-24 07:53 UTC, mkundeev commented on src/sass/components/_contacts.scss
> +            margin: 0 auto 81px;
Зачем нижний margin для планшета и десктопа?

2022-04-24 07:53 UTC, mkundeev commented on src/partials/contacts.html
> -        <ul class="contacts__list">
Карточки контактов должны быть элементами списка а не каждая отдельным списком

2022-04-24 07:53 UTC, mkundeev commented on src/partials/contacts.html
> -
в списке расписания должно быть два элемента li. В каждом элементе li должно быть два элемента (p, span, b ... на твое усмотрение) один с днями неделе а второй со временем

2022-04-25 09:56 UTC, KocherhanIrina commented on src/partials/contacts.html
> -        <ul class="contacts__list">
fix

2022-04-25 09:56 UTC, KocherhanIrina commented on src/partials/contacts.html
> -
fix

2022-04-25 17:46 UTC, mkundeev approved these changes

2022-04-25 17:46 UTC, merged